# import sqlalchemy

"""
[
lista y listaTCA: Usado para subir paquetes de vuelta sintys.
namesList y dtypeDictCSV: Usado para dar titulo y tipos de dato a la lectura SOMOSO.
dtypeDictSQL: Los tipos de dato para subir el dataframe a la DB.
dtypeDictNomsXLS: Dar tipo a las columnas del excel a leer paar el cruce NOMS.
]
"""

# Listas para vueltas Sintys
lista = [
    {
        "Nombre": "B00",
        "dtype": {
            "id_persona ": str,
            " QID  ": str,
            " BASE  ": "category",
            " CORTE  ": "category",
            " CUIT  ": str,
            " TDOC  ": "category",
            " NDOC  ": str,
            " SEXO  ": "category",
            " DENO  ": str,
            " FNAC  ": str,
            " MONTO  ": str,
            " PROV  ": str,
            " PERIODO  ": str,
            " PERIODO_BASE  ": "category",
            " PERIODO_ACT  ": "category",
            " BASE_PROV  ": "category",
            " PASAPORTE  ": str,
            " TIPO_EF  ": "category",
            " NRO_FORMULARIO  ": str,
            " APELLIDO_ORIG  ": str,
            " NOMBRE_ORIG  ": str,
            " FNAC_ORIG  ": str,
            " SEXO_ORIGEN  ": str,
            " TDOC_ORIG  ": "category",
            " NDOC_ORIG  ": "category",
            " PAIS_ORIGEN  ": "category",
            " CALLE  ": str,
            " NUMERO  ": str,
            " PISO  ": str,
            " DEPTO  ": str,
            " MANZANA  ": str,
            " TORRE  ": str,
            " TIPO_DATO_ADIC  ": str,
            " DATO_ADICIONAL  ": str,
            " LOCALIDAD  ": str,
            " COD_POST  ": str,
            " MUNICIPIO  ": str,
            " OTRO_MUNICIPIO  ": str,
            " PROV_ORIG  ": "category",
            " TELEFONO  ": str,
            " OCUPACION  ": str,
            " DESCR_TRABAJO  ": str,
            " COD_ACTIVIDAD  ": str,
            " ACTIVIDAD ": str,
            " LOCAL_ACTIVIDAD  ": str,
            " PROV_ACTIVIDAD  ": str,
            " OBRA  ": str,
            " COOP_PROYECTO  ": str,
            " CUIT_ORIG  ": str,
            " RESOLUCION  ": str,
            " CAMPO1  ": str,
            " PERIODO_ORIGINAL  ": str,
            " PROG  ": str,
            " MONTOPRG  ": str,
            " MONTOREDLES  ": str,
            " MONTO_ORIG  ": str,
            " ESTADO_SINTYS  ": "category",
            " TIPO_PRESTACION_SINTYS  ": str,
            " TIPO_BENEFICIARIO_SINTYS  ": str,
            " CANAL_FINANCIACION_SINTYS  ": str,
            " SUBPROGRAMA_SINTYS  ": str,
        },
    },
    {
        "Nombre": "DATOS",
        "dtype": {
            "id_persona": str,
            "cuit": str,
            "tdoc": "category",
            "ndoc": str,
            "deno": str,
            "sexo": "category",
            "fnac": str,
            "grado_confiab": str,
        },
    },
    {
        "Nombre": "EMBARCACIONES",
        "dtype": {
            "ID_PERSONA": str,
            "BASE": "category",
            "PERIODO_BASE": "category",
            "MATRICULA": str,
            "DOMICILIO": str,
            "COD_POSTAL": str,
            "LOCALIDAD": "category",
            "PROV": "category",
            "FEC_INSCRIPCION": str,
            "VALUACION": str,
            "TIPO_EMBARCACION": str,
        },
    },
    {
        "Nombre": "AERONAVES",
        "dtype": {
            "ID_PERSONA": str,
            "BASE": "category",
            "PERIODO_BASE": "category",
            "PROVINCIA": "category",
            "DOMICILIO_PART_SOC": str,
            "LOCALIDAD_PART_SOC": str,
            "MATRICULA": str,
            "TIPO01": str,
            "VALUACION": str,
        },
    },
    {
        "Nombre": "EMPLEO_DEPENDIENTE",
        "dtype": {
            "ID_PERSONA": str,
            "SECTOR": "category",
            "TIPO_EMPLEO_PUBLICO": str,
            "BASE": "category",
            "SITUACION_LABORAL": str,
            "PERIODO_BASE": "category",
            "MONTO": str,
            "CUIT_EMPLEADOR": str,
            "DENO_EMPLEADOR": str,
        },
    },
    {
        "Nombre": "EMPLEO_INDEPENDIENTE",
        "dtype": {
            "ID_PERSONA": str,
            "BASE": "category",
            "PERIODO_BASE": "category",
            "CATEGORIA": "category",
        },
    },
    {
        "Nombre": "FALLECIDOS",
        "dtype": {
            "ID_PERSONA": str,
            "ANIO": "category",
            "ACTA": str,
            "TOMO": str,
            "FOLIO": str,
            "SECCIONAL": str,
            "FFALL": str,
            "ANOACTA": str,
            "IMAGEN_TIFF": str,
            "BASE": str,
        },
    },
    {
        "Nombre": "INMUEBLES",
        "dtype": {
            "ID_PERSONA": str,
            "BASE": "category",
            "PERIODO_BASE": "category",
            "DOMICILIO_FISCAL": str,
            "CALLE": str,
            "NUMERO": str,
            "PISO": str,
            "APARTAMENTO": str,
            "COD_POSTAL": str,
            "LOCALIDAD": str,
            "DEPARTAMENTO": str,
            "PROVINCIA": "category",
            "NC_NOMENCLATURA": str,
            "NC_PARTIDO": str,
            "NC_DEPARTAMENTO": str,
            "NC_DISTRITO": str,
            "NC_CIRCUNSCRIPCION": str,
            "NC_SECCION": str,
            "NC_FRACCION": str,
            "NC_MANZANA": str,
            "NC_PARCELA": str,
            "NC_CHACRA": str,
            "NC_QUINTA": str,
            "NC_LOTE": str,
            "NC_UNIC_FUNCIONAL": str,
            "FECHA_INSCRIPCION": str,
            "PARTIDA": str,
            "MATRICULA": str,
        },
    },
    {
        "Nombre": "JUBILACIONES_PENSIONES",
        "dtype": {
            "ID_PERSONA": str,
            "TBENE": str,
            "BASE": "category",
            "PERIODO_BASE": "category",
            "LEY_APLICADA": str,
            "MONTO": str,
            "DESC_BENE": str,
        },
    },
    {
        "Nombre": "PADRON_AUTOMOTORES",
        "dtype": {
            "ID_PERSONA": str,
            "BASE": "category",
            "PERIODO_BASE": "category",
            "PROVINCIA": "category",
            "DOMINIO": str,
            "FECHA_TITU_DESDE": str,
            "CALLE": str,
            "NUMERO": str,
            "PISO": str,
            "DEPTO": str,
            "COD_POSTAL": str,
            "LOCALIDAD": str,
            # "MODELO": str, en 202008 dejo de llegar de sintys
            "FECHA_INSCRIPCION": str,
            "USO_VEHICULO": str,
            "TIPO_AUTOMOTOR_NAC": str,
            "TIPO_AUTOMOTOR_IMP": str,
        },
    },
    {
        "Nombre": "PERSONAS_JURIDICAS",
        "dtype": {
            "ID_PERSONA": str,
            "BASE": "category",
            "PERIODO_BASE": "category",
            "PROVINCIA": "category",
            "FECHA_INGRESO": str,
            "FECHA_EGRESO": str,
            "DOMICILIO_ACC": str,
            "CALLE_ACC": str,
            "NUMERO_ACC": str,
            "PISO_ACC": str,
            "DEPTO_ACC": str,
            "COD_POST_ACC": str,
            "LOCALIDAD_ACC": str,
            "COD_LOC_ACC": str,
            "DEPARTAMENTO_ACC": str,
            "COD_DEPARTAMENTO_ACC": str,
            "TIPO_SOC": "category",
            "DENO_SOC": str,
            "CUIT_SOC": str,
            "DOMICILIO_SOC": str,
            "CALLE_SOC": str,
            "NUMERO_SOC": str,
            "PISO_SOC": str,
            "DEPTO_SOC": str,
            "COD_POST_SOC": str,
            "LOCALIDAD_SOC": str,
            "COD_LOCALIDAD_SOC": str,
            "DEPARTAMENTO_SOC": str,
            "COD_DEPARTAMENTO_SOC": str,
            "PROVINCIA_SOC": "category",
            "FECHA_CONSTITUCION": str,
            "NRO_LEGAJO": str,
        },
    },
    {
        "Nombre": "PNC",
        "dtype": {
            "ID_PERSONA": str,
            "TBENE": str,
            "BASE": "category",
            "PERIODO_BASE": "category",
            "LEY_APLICADA": str,
            "MONTO": str,
            "DESC_BENE": str,
            # "SUB_TBENE": str,
        },
    },
    {
        "Nombre": "RUBPS",
        "dtype": {
            "ID_PERSONA": str,
            "TIPO_PRESTACION": str,
            "BASE": "category",
            "PERIODO_BASE": "category",
            "MONTO": str,
        },
    },
    {
        "Nombre": "ASIGNACIONES",
        "dtype": {
            "ID_PERSONA": str,
            "BASE": "category",
            "PERIODO_BASE": "category",
            "TIPO_BEN": str,
            "TIPO_PRESTACION": str,
        },
    },
]

listaTCA = [
    {"Nombre": "TCA_100", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_200", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_302", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5249", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5375", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5396", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5397", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5399", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5402", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5406", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5407", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5411", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5453", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5501", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5550", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5588", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5604", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5605", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
    {"Nombre": "TCA_5678", "dtype": {"CODIGO": str, "DESCRIPCION": str}},
]
